mail.transport.protocol=smtp
mail.smtp.starttls.enable=false
mail.smtp.host=mail.valterestevam.com.br
mail.smtp.auth=true
mail.smtp.user=noreply.demo@valterestevam.com.br
mail.debug=true
mail.smtp.port=587
passwd=mypasswd